//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishQuestion.LocalizeResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishQuestion.LocalizeResource.AppCommonResource", typeof(AppCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the audio file. Please check setting audio directory!.
        /// </summary>
        public static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files path cannot empty.
        /// </summary>
        public static string AudioPathEmptyMessage {
            get {
                return ResourceManager.GetString("AudioPathEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        public static string B1 {
            get {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2.
        /// </summary>
        public static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete question when number of question less than number question in paragraph.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select empty answer.
        /// </summary>
        public static string CannotSelectEmptyAnswer {
            get {
                return ResourceManager.GetString("CannotSelectEmptyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config key is already existed.
        /// </summary>
        public static string ConfigExisted {
            get {
                return ResourceManager.GetString("ConfigExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Confirm#.
        /// </summary>
        public static string ConfirmCaption {
            get {
                return ResourceManager.GetString("ConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete item?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting audio directory is not found, Do you want to create and copy the audio file to?.
        /// </summary>
        public static string CreateAudioDirectoryMessage {
            get {
                return ResourceManager.GetString("CreateAudioDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bias between total time: {0} and real time: {1} is so much ({2} minute), Do you agree and continue?.
        /// </summary>
        public static string DateDiffTime {
            get {
                return ResourceManager.GetString("DateDiffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question {0} has empty content/Title.
        /// </summary>
        public static string EmptyContent {
            get {
                return ResourceManager.GetString("EmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Error#.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide A.
        /// </summary>
        public static string GuideA {
            get {
                return ResourceManager.GetString("GuideA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide B.
        /// </summary>
        public static string GuideB {
            get {
                return ResourceManager.GetString("GuideB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide B1.
        /// </summary>
        public static string GuideB1 {
            get {
                return ResourceManager.GetString("GuideB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide B2.
        /// </summary>
        public static string GuideB2 {
            get {
                return ResourceManager.GetString("GuideB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide C.
        /// </summary>
        public static string GuideC {
            get {
                return ResourceManager.GetString("GuideC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.htm)|*.htm|All files (*.html)|*.html.
        /// </summary>
        public static string HtmlFilter {
            get {
                return ResourceManager.GetString("HtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg files (*.jpg)|*.jpg|All files (*.png.*)|*.png|All files (*.gif)|*.gif|All files (*.*)|*.*.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Info#.
        /// </summary>
        public static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key and value cannot empty.
        /// </summary>
        public static string KeyValueNotEmpty {
            get {
                return ResourceManager.GetString("KeyValueNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TABLE title=&quot;&quot; height=100 cellSpacing=0 width=&quot;95%&quot; border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD width=&quot;48%&quot;&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Department of Education &amp;amp; Trainning&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Ho Chi Minh City&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;HR/&gt;
        ///&lt;/TD&gt;
        ///&lt;TD width=&quot;15%&quot;&gt;&lt;/TD&gt;
        ///&lt;TD width=&quot;32%&quot;&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Level: ELEMENTARY&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;LISTENING TEST&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Date: {0}&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&amp;nbsp; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LevelAListeningHeader {
            get {
                return ResourceManager.GetString("LevelAListeningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=5&gt;ĐỀ {0}&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;br/&gt;
        ///&lt;HR/&gt;
        ///&lt;P&gt;
        ///&lt;TABLE title=&quot;&quot; height=100 cellSpacing=0 width=&quot;95%&quot; border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD width=&quot;48%&quot;&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Department of Education &amp;amp; Trainning&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Ho Chi Minh City&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;/TD&gt;
        ///&lt;TD width=&quot;15%&quot;&gt;&lt;/TD&gt;
        ///&lt;TD width=&quot;32%&quot;&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Level: ELEMENTARY&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Date: {1}&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LevelAWritingHeader {
            get {
                return ResourceManager.GetString("LevelAWritingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TABLE title=&quot;&quot; height=100 cellSpacing=0 width=&quot;95%&quot; border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD width=&quot;50%&quot;&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Department of Education &amp;amp; Trainning&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Ho Chi Minh City&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;HR/&gt;
        ///&lt;/TD&gt;
        ///&lt;TD width=&quot;15%&quot;&gt;&lt;/TD&gt;
        ///&lt;TD width=&quot;30%&quot;&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Level: ELEMENTARY&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;LISTENING TEST&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;Date: {0}&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P&gt;&amp;nbsp; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LevelBListeningHeader {
            get {
                return ResourceManager.GetString("LevelBListeningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;ĐỀ THI NÂNG NGẠCH&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;P align=center&gt;&lt;STRONG&gt;&lt;FONT size=4&gt;TỪ CHUYÊN VIÊN LÊN CHUYÊN VIÊN CHÍNH&lt;/FONT&gt;&lt;/STRONG&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;P align=center&gt;Thời gian: {0}&lt;/P&gt;
        ///&lt;P align=center&gt;{1}&lt;/P&gt;
        ///&lt;P align=left&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;P align=left&gt;&amp;nbsp;&lt;/P&gt;
        ///&lt;TABLE title=&quot;&quot; height=100 cellSpacing=0 width=&quot;95%&quot; border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD&gt;
        ///&lt;P&gt;Họ và tên: .......................................................&lt;/P&gt;
        ///&lt;P&gt;Ngày sinh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LevelBWritingHeader {
            get {
                return ResourceManager.GetString("LevelBWritingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;P&gt;
        ///&lt;TABLE title=&quot;&quot; height=100 cellSpacing=0 width=&quot;95%&quot; border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD width=&quot;50%&quot;&gt;
        ///&lt;P align=center&gt;&lt;FONT size=4&gt;Institute of Formation and Promotion&lt;/FONT&gt;&lt;/P&gt;
        ///&lt;P align=center&gt;&lt;FONT size=4&gt;Ho Chi Minh City&lt;/FONT&gt;&lt;/P&gt;&lt;/TD&gt;
        ///&lt;TD width=&quot;15%&quot;&gt;&lt;/TD&gt;
        ///&lt;TD width=&quot;30%&quot;&gt;
        ///&lt;P&gt;&lt;FONT size=4&gt;Level: &lt;STRONG&gt;Advance&lt;/STRONG&gt;&lt;/FONT&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;FONT size=4&gt;Date of Testing: {0}&lt;/FONT&gt;&lt;/P&gt;
        ///&lt;P&gt;&lt;FONT size=4&gt;Time allotted: {1}&lt;/FONT&gt;&lt;/P&gt;&lt;/TD&gt;&lt;/TR&gt;&lt;/TBODY&gt;&lt;/TABLE&gt;&lt;/P&gt;
        ///&lt;P&gt;&amp;nbsp;&lt;/P&gt;.
        /// </summary>
        public static string LevelCHeader {
            get {
                return ResourceManager.GetString("LevelCHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test level not found.
        /// </summary>
        public static string LevelNotFound {
            get {
                return ResourceManager.GetString("LevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key is not correct, please contact with admin to receive the key.
        /// </summary>
        public static string LicenseFailMessage {
            get {
                return ResourceManager.GetString("LicenseFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose an correct answer.
        /// </summary>
        public static string MustChooseAnswer {
            get {
                return ResourceManager.GetString("MustChooseAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;English Test&lt;/TITLE&gt;
        ///&lt;META content=&quot;text/html; charset=ISO-8859-1&quot; http-equiv=content-type&gt;
        ///&lt;STYLE type=text/css&gt;
        ///p {
        ///margin-bottom: 10;
        ///margin-top: 10;
        ///}
        ///&lt;/STYLE&gt;
        ///
        ///&lt;META name=GENERATOR content=&quot;MSHTML 11.00.9600.17963&quot;&gt;&lt;/HEAD&gt;
        ///&lt;BODY&gt;
        ///&lt;P&gt;&amp;nbsp;&lt;/P&gt;&lt;/BODY&gt;&lt;/HTML&gt;.
        /// </summary>
        public static string NewHtml {
            get {
                return ResourceManager.GetString("NewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No question is selected.
        /// </summary>
        public static string NoSelectedQuestion {
            get {
                return ResourceManager.GetString("NoSelectedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough question to generate.
        /// </summary>
        public static string NotEnoughQuestion {
            get {
                return ResourceManager.GetString("NotEnoughQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select test content to save.
        /// </summary>
        public static string NotSelectedSubTest {
            get {
                return ResourceManager.GetString("NotSelectedSubTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs test must greater than 0.
        /// </summary>
        public static string NumOfSubTestGreaterThan0 {
            get {
                return ResourceManager.GetString("NumOfSubTestGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open audio folder path.
        /// </summary>
        public static string OpenAudioPath {
            get {
                return ResourceManager.GetString("OpenAudioPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question cannot empty.
        /// </summary>
        public static string PopupQuestionEmpty {
            get {
                return ResourceManager.GetString("PopupQuestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register success.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not found.
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/.
        /// </summary>
        public static string SettingDefaultAudioFilePath {
            get {
                return ResourceManager.GetString("SettingDefaultAudioFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTest.
        /// </summary>
        public static string SubTest {
            get {
                return ResourceManager.GetString("SubTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Success#.
        /// </summary>
        public static string SussessCaption {
            get {
                return ResourceManager.GetString("SussessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Warning#.
        /// </summary>
        public static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
    }
}
