//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishQuestion.MainApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishQuestion.MainApp.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ActionAdd {
            get {
                return ResourceManager.GetString("ActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ActionSave {
            get {
                return ResourceManager.GetString("ActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit question.
        /// </summary>
        internal static string AddEditQuestionAnswer {
            get {
                return ResourceManager.GetString("AddEditQuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session I. Listen to the recording and decide whether each statement is TRUE of FALSE. Write TRUE or FALSE in the space given in the answer sheet..
        /// </summary>
        internal static string AListeningSession1 {
            get {
                return ResourceManager.GetString("AListeningSession1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session II. Listen to the recording and choose the best option (A, B, C or D) to fill in each blank..
        /// </summary>
        internal static string AListeningSession2 {
            get {
                return ResourceManager.GetString("AListeningSession2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session III. Listeng to the recording and give short answer to the following questions..
        /// </summary>
        internal static string AListeningSession3 {
            get {
                return ResourceManager.GetString("AListeningSession3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section I.
        /// </summary>
        internal static string ALSection1 {
            get {
                return ResourceManager.GetString("ALSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section II.
        /// </summary>
        internal static string ALSection2 {
            get {
                return ResourceManager.GetString("ALSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section III.
        /// </summary>
        internal static string ALSection3 {
            get {
                return ResourceManager.GetString("ALSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and decide whether each statement is TRUE or FALSE. Write TRUE or FALSE in the space given in the answer sheet..
        /// </summary>
        internal static string ALToolTip1 {
            get {
                return ResourceManager.GetString("ALToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and choose the best option (A, B or C) to fill in each blank..
        /// </summary>
        internal static string ALToolTip2 {
            get {
                return ResourceManager.GetString("ALToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and give short answers to the following questions..
        /// </summary>
        internal static string ALToolTip3 {
            get {
                return ResourceManager.GetString("ALToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A..
        /// </summary>
        internal static string AnswerA {
            get {
                return ResourceManager.GetString("AnswerA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B..
        /// </summary>
        internal static string AnswerB {
            get {
                return ResourceManager.GetString("AnswerB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C..
        /// </summary>
        internal static string AnswerC {
            get {
                return ResourceManager.GetString("AnswerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D..
        /// </summary>
        internal static string AnswerD {
            get {
                return ResourceManager.GetString("AnswerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer list.
        /// </summary>
        internal static string AnswerList {
            get {
                return ResourceManager.GetString("AnswerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section I.
        /// </summary>
        internal static string ARSection1 {
            get {
                return ResourceManager.GetString("ARSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section II.
        /// </summary>
        internal static string ARSection2 {
            get {
                return ResourceManager.GetString("ARSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section III.
        /// </summary>
        internal static string ARSection3 {
            get {
                return ResourceManager.GetString("ARSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section IV - A.
        /// </summary>
        internal static string ARSection4A {
            get {
                return ResourceManager.GetString("ARSection4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section IV - B.
        /// </summary>
        internal static string ARSection4B {
            get {
                return ResourceManager.GetString("ARSection4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the word or phrase that best completes the sentence..
        /// </summary>
        internal static string ARToolTip1 {
            get {
                return ResourceManager.GetString("ARToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the item (A, B, C, or D) that best completes the unfinished statement or answers the question about the passage.
        /// </summary>
        internal static string ARToolTip2 {
            get {
                return ResourceManager.GetString("ARToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the word or phrase (A, B, C, or D) that best fits the blank space..
        /// </summary>
        internal static string ARToolTip3 {
            get {
                return ResourceManager.GetString("ARToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all necessary changes and additions to produce a complete sentence from each of the following sets of words and phrases.
        /// </summary>
        internal static string ARToolTip4A {
            get {
                return ResourceManager.GetString("ARToolTip4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the unfinished sentence in such a way that it means the same as the sentence printed before it..
        /// </summary>
        internal static string ARToolTip4B {
            get {
                return ResourceManager.GetString("ARToolTip4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and decide whether each statement is TRUE of FLASE. Write TRUE or FALSE in the space given in the answer sheet..
        /// </summary>
        internal static string ATitleListeningSection1 {
            get {
                return ResourceManager.GetString("ATitleListeningSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and choose the best option (A, B, or C) to fill each blank..
        /// </summary>
        internal static string ATitleListeningSection2 {
            get {
                return ResourceManager.GetString("ATitleListeningSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and give short answers to the following questions..
        /// </summary>
        internal static string ATitleListeningSection3 {
            get {
                return ResourceManager.GetString("ATitleListeningSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the word or phrase that best completes the sentence..
        /// </summary>
        internal static string ATitleSection1 {
            get {
                return ResourceManager.GetString("ATitleSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the item (A, B, C or D) that best completes the unfinished statement or answers the question about the passage..
        /// </summary>
        internal static string ATitleSection2 {
            get {
                return ResourceManager.GetString("ATitleSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the item (A, B, C or D) that best fits the blank space..
        /// </summary>
        internal static string ATitleSection3 {
            get {
                return ResourceManager.GetString("ATitleSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all necessary changes and additions to produce a complete sentence from each of the following sets of words and phrases..
        /// </summary>
        internal static string ATitleSection4A {
            get {
                return ResourceManager.GetString("ATitleSection4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the unfinished sentence in such a way that it means the same as the sentence printed before it..
        /// </summary>
        internal static string ATitleSection4B {
            get {
                return ResourceManager.GetString("ATitleSection4B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio folder path.
        /// </summary>
        internal static string AudioPath {
            get {
                return ResourceManager.GetString("AudioPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        internal static string B1LSection1 {
            get {
                return ResourceManager.GetString("B1LSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        internal static string B1LSection2 {
            get {
                return ResourceManager.GetString("B1LSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3.
        /// </summary>
        internal static string B1LSection3 {
            get {
                return ResourceManager.GetString("B1LSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 4.
        /// </summary>
        internal static string B1LSection4 {
            get {
                return ResourceManager.GetString("B1LSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1LToolTip1 {
            get {
                return ResourceManager.GetString("B1LToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1LToolTip2 {
            get {
                return ResourceManager.GetString("B1LToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1LToolTip3 {
            get {
                return ResourceManager.GetString("B1LToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1LToolTip4 {
            get {
                return ResourceManager.GetString("B1LToolTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        internal static string B1RSection1 {
            get {
                return ResourceManager.GetString("B1RSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        internal static string B1RSection2 {
            get {
                return ResourceManager.GetString("B1RSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3.
        /// </summary>
        internal static string B1RSection3 {
            get {
                return ResourceManager.GetString("B1RSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 4.
        /// </summary>
        internal static string B1RSection4 {
            get {
                return ResourceManager.GetString("B1RSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 5.
        /// </summary>
        internal static string B1RSection5 {
            get {
                return ResourceManager.GetString("B1RSection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1RToolTip1 {
            get {
                return ResourceManager.GetString("B1RToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1RToolTip2 {
            get {
                return ResourceManager.GetString("B1RToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1RToolTip3 {
            get {
                return ResourceManager.GetString("B1RToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1RToolTip4 {
            get {
                return ResourceManager.GetString("B1RToolTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1RToolTip5 {
            get {
                return ResourceManager.GetString("B1RToolTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        internal static string B1WSection1 {
            get {
                return ResourceManager.GetString("B1WSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        internal static string B1WSection2 {
            get {
                return ResourceManager.GetString("B1WSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3.
        /// </summary>
        internal static string B1WSection3 {
            get {
                return ResourceManager.GetString("B1WSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1WToolTip1 {
            get {
                return ResourceManager.GetString("B1WToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1WToolTip2 {
            get {
                return ResourceManager.GetString("B1WToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B1WToolTip3 {
            get {
                return ResourceManager.GetString("B1WToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session I. Listen to the recording and decide whether each statement is TRUE of FALSE. Write TRUE or FALSE in the space given in the answer sheet..
        /// </summary>
        internal static string BListeningSessionA {
            get {
                return ResourceManager.GetString("BListeningSessionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session II. Listen to the recording and choose the best option (A, B, C or D) to fill in each blank..
        /// </summary>
        internal static string BListeningSessionB {
            get {
                return ResourceManager.GetString("BListeningSessionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session III. Listeng to the recording and give short answer to the following questions..
        /// </summary>
        internal static string BListeningSessionC {
            get {
                return ResourceManager.GetString("BListeningSessionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 1.
        /// </summary>
        internal static string BRSection1 {
            get {
                return ResourceManager.GetString("BRSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 2.
        /// </summary>
        internal static string BRSection2 {
            get {
                return ResourceManager.GetString("BRSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 3.
        /// </summary>
        internal static string BRSection3 {
            get {
                return ResourceManager.GetString("BRSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 4.
        /// </summary>
        internal static string BRSection4 {
            get {
                return ResourceManager.GetString("BRSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 5.
        /// </summary>
        internal static string BRSection5 {
            get {
                return ResourceManager.GetString("BRSection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you must choose the word or phrase which best completes each underlined word or phrase or choose the word or phrase which best completes each sentence..
        /// </summary>
        internal static string BRToolTip1 {
            get {
                return ResourceManager.GetString("BRToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the passage and choose the best answer..
        /// </summary>
        internal static string BRToolTip2 {
            get {
                return ResourceManager.GetString("BRToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the gaps with the most suitable words..
        /// </summary>
        internal static string BRToolTip3 {
            get {
                return ResourceManager.GetString("BRToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence transformation..
        /// </summary>
        internal static string BRToolTip4 {
            get {
                return ResourceManager.GetString("BRToolTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a composition from 100 to 120 words on the specific/given topic..
        /// </summary>
        internal static string BRToolTip5 {
            get {
                return ResourceManager.GetString("BRToolTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this session you must choose the word or phrase which best completes each underlined word or phrase or choose the word or phrase with best completes each sentence..
        /// </summary>
        internal static string BSectionA {
            get {
                return ResourceManager.GetString("BSectionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the passage and choose the best answer..
        /// </summary>
        internal static string BSectionB {
            get {
                return ResourceManager.GetString("BSectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the gaps with the most suitable words..
        /// </summary>
        internal static string BSectionC {
            get {
                return ResourceManager.GetString("BSectionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence transformation..
        /// </summary>
        internal static string BSectionD {
            get {
                return ResourceManager.GetString("BSectionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a composition from 100 to 120 words on the specific/given topic..
        /// </summary>
        internal static string BSectionE {
            get {
                return ResourceManager.GetString("BSectionE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section A.
        /// </summary>
        internal static string BTitleSection1 {
            get {
                return ResourceManager.GetString("BTitleSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section B.
        /// </summary>
        internal static string BTitleSection2 {
            get {
                return ResourceManager.GetString("BTitleSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section C.
        /// </summary>
        internal static string BTitleSection3 {
            get {
                return ResourceManager.GetString("BTitleSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section D.
        /// </summary>
        internal static string BTitleSection4 {
            get {
                return ResourceManager.GetString("BTitleSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section E.
        /// </summary>
        internal static string BTitleSection5 {
            get {
                return ResourceManager.GetString("BTitleSection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can mix answer.
        /// </summary>
        internal static string CanMixAnswer {
            get {
                return ResourceManager.GetString("CanMixAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose class.
        /// </summary>
        internal static string ChooseClass {
            get {
                return ResourceManager.GetString("ChooseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose level.
        /// </summary>
        internal static string ChooseLevel {
            get {
                return ResourceManager.GetString("ChooseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Manual.
        /// </summary>
        internal static string ChooseManual {
            get {
                return ResourceManager.GetString("ChooseManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose purpose.
        /// </summary>
        internal static string ChoosePurpose {
            get {
                return ResourceManager.GetString("ChoosePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1: Listen to recording and fill in each gap the word you&apos;ve heard..
        /// </summary>
        internal static string CListeningSession1 {
            get {
                return ResourceManager.GetString("CListeningSession1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2: Listen to the recording and write T (True) or F (False) on the underlined part..
        /// </summary>
        internal static string CListeningSession2 {
            get {
                return ResourceManager.GetString("CListeningSession2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3: Listen to the recording about the questions that the people are asked about their jobs. Write one question that each person is asked..
        /// </summary>
        internal static string CListeningSession3 {
            get {
                return ResourceManager.GetString("CListeningSession3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current page.
        /// </summary>
        internal static string ClosePage {
            get {
                return ResourceManager.GetString("ClosePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1.
        /// </summary>
        internal static string CLSection1 {
            get {
                return ResourceManager.GetString("CLSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2.
        /// </summary>
        internal static string CLSection2 {
            get {
                return ResourceManager.GetString("CLSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3.
        /// </summary>
        internal static string CLSection3 {
            get {
                return ResourceManager.GetString("CLSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 1: Listen to the recording and fill in each gap the word you&apos;re heard..
        /// </summary>
        internal static string CLTitle1 {
            get {
                return ResourceManager.GetString("CLTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 2: Listen to the recording and write T (True) or F (False) on the underline part..
        /// </summary>
        internal static string CLTitle2 {
            get {
                return ResourceManager.GetString("CLTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part 3:Listen to the recording about the questions that the people are asked about their job. Write one question that each person is asked..
        /// </summary>
        internal static string CLTitle3 {
            get {
                return ResourceManager.GetString("CLTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and fill in each gap the word you&apos;ve heard..
        /// </summary>
        internal static string CLToolTip1 {
            get {
                return ResourceManager.GetString("CLToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording and write T (True) or F (False) on the underlined part..
        /// </summary>
        internal static string CLToolTip2 {
            get {
                return ResourceManager.GetString("CLToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to the recording..
        /// </summary>
        internal static string CLToolTip3 {
            get {
                return ResourceManager.GetString("CLToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Test.
        /// </summary>
        internal static string ComposeTest {
            get {
                return ResourceManager.GetString("ComposeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio path.
        /// </summary>
        internal static string ConfigAudioFilePath {
            get {
                return ResourceManager.GetString("ConfigAudioFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Template.
        /// </summary>
        internal static string ConfigB1B2 {
            get {
                return ResourceManager.GetString("ConfigB1B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section A.
        /// </summary>
        internal static string CRSectionA {
            get {
                return ResourceManager.GetString("CRSectionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section B.
        /// </summary>
        internal static string CRSectionB {
            get {
                return ResourceManager.GetString("CRSectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this session you must choose the word or phrase which best completes each sentence. For each question, indicate the letter A, B, C or D againt the number of the question..
        /// </summary>
        internal static string CRTitleSectionA {
            get {
                return ResourceManager.GetString("CRTitleSectionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this session you find after the passage some question of unfinished statements about the passage, each with four suggested answers or ways of finishing. You must choose the one which you think fits best. For each question, indicate the letter A, B, C or D againt the number of the question..
        /// </summary>
        internal static string CRTitleSectionB {
            get {
                return ResourceManager.GetString("CRTitleSectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you must choose the word or phrase which best completes each sentence. For each question, indicate the letter A, B, C, or D against the number of the question..
        /// </summary>
        internal static string CRToolTip1 {
            get {
                return ResourceManager.GetString("CRToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you will find after the passage give questions of unfinished statements about the passage, each with four suggested answers or ways of finishing. You must choose the one which you think fits best..
        /// </summary>
        internal static string CRToolTip2 {
            get {
                return ResourceManager.GetString("CRToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section A - A.
        /// </summary>
        internal static string CWSection1A {
            get {
                return ResourceManager.GetString("CWSection1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section A - B.
        /// </summary>
        internal static string CWSection1B {
            get {
                return ResourceManager.GetString("CWSection1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section A - C.
        /// </summary>
        internal static string CWSection1C {
            get {
                return ResourceManager.GetString("CWSection1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section B.
        /// </summary>
        internal static string CWSection2 {
            get {
                return ResourceManager.GetString("CWSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITING
        ///SECTION A
        ///USE OF ENGLISH.
        /// </summary>
        internal static string CWSectionA {
            get {
                return ResourceManager.GetString("CWSectionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Fill each of the numbered blanks in the following passage. Use only ONE word in each space..
        /// </summary>
        internal static string CWTitleSectionAA {
            get {
                return ResourceManager.GetString("CWTitleSectionAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. GUILD SENTENCE BUILDING.
        ///Building a complete sentence with the given words..
        /// </summary>
        internal static string CWTitleSectionAB {
            get {
                return ResourceManager.GetString("CWTitleSectionAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. Rewrite the following sentences without changing their original meaning. Begin with the given words..
        /// </summary>
        internal static string CWTitleSectionAC {
            get {
                return ResourceManager.GetString("CWTitleSectionAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a composition from 80 to 120 words on the topic..
        /// </summary>
        internal static string CWTitleSectionB {
            get {
                return ResourceManager.GetString("CWTitleSectionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill each of the numbered blanks in the following passage. Use only ONE word in each space..
        /// </summary>
        internal static string CWToolTip1 {
            get {
                return ResourceManager.GetString("CWToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building a complete sentence with the given words..
        /// </summary>
        internal static string CWToolTip2 {
            get {
                return ResourceManager.GetString("CWToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the following sentences without changing their original meaning. Begin with the given words..
        /// </summary>
        internal static string CWToolTip3 {
            get {
                return ResourceManager.GetString("CWToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General setting.
        /// </summary>
        internal static string GeneralSetting {
            get {
                return ResourceManager.GetString("GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Test.
        /// </summary>
        internal static string GenerateTest {
            get {
                return ResourceManager.GetString("GenerateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate web test.
        /// </summary>
        internal static string GenerateWebTest {
            get {
                return ResourceManager.GetString("GenerateWebTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key template.
        /// </summary>
        internal static string KeyTemplate {
            get {
                return ResourceManager.GetString("KeyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level A.
        /// </summary>
        internal static string LevelA {
            get {
                return ResourceManager.GetString("LevelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level B.
        /// </summary>
        internal static string LevelB {
            get {
                return ResourceManager.GetString("LevelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level B1.
        /// </summary>
        internal static string LevelB1 {
            get {
                return ResourceManager.GetString("LevelB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level B2.
        /// </summary>
        internal static string LevelB2 {
            get {
                return ResourceManager.GetString("LevelB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level C.
        /// </summary>
        internal static string LevelC {
            get {
                return ResourceManager.GetString("LevelC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTENING COMPREHENSION.
        /// </summary>
        internal static string ListeningComprehension {
            get {
                return ResourceManager.GetString("ListeningComprehension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NumberOfQuestion {
            get {
                return ResourceManager.GetString("NumberOfQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph detail.
        /// </summary>
        internal static string ParagraphDetail {
            get {
                return ResourceManager.GetString("ParagraphDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph list.
        /// </summary>
        internal static string ParagraphList {
            get {
                return ResourceManager.GetString("ParagraphList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question detail.
        /// </summary>
        internal static string QuestionDetail {
            get {
                return ResourceManager.GetString("QuestionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question list.
        /// </summary>
        internal static string QuestionList {
            get {
                return ResourceManager.GetString("QuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph &amp; answer.
        /// </summary>
        internal static string RPA {
            get {
                return ResourceManager.GetString("RPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph, question &amp; answer.
        /// </summary>
        internal static string RPQA {
            get {
                return ResourceManager.GetString("RPQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question &amp; answer.
        /// </summary>
        internal static string RQA {
            get {
                return ResourceManager.GetString("RQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert section title.
        /// </summary>
        internal static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type.
        /// </summary>
        internal static string SubType {
            get {
                return ResourceManager.GetString("SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test content.
        /// </summary>
        internal static string TestContent {
            get {
                return ResourceManager.GetString("TestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test information.
        /// </summary>
        internal static string TestInfo {
            get {
                return ResourceManager.GetString("TestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string TestInfoClass {
            get {
                return ResourceManager.GetString("TestInfoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess test.
        /// </summary>
        internal static string TestInfoIsGuess {
            get {
                return ResourceManager.GetString("TestInfoIsGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string TestInfoLevel {
            get {
                return ResourceManager.GetString("TestInfoLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TestInfoName {
            get {
                return ResourceManager.GetString("TestInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTests.
        /// </summary>
        internal static string TestInfoNumOfSubTest {
            get {
                return ResourceManager.GetString("TestInfoNumOfSubTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string TestInfoPurpose {
            get {
                return ResourceManager.GetString("TestInfoPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test date.
        /// </summary>
        internal static string TestInfoTestDate {
            get {
                return ResourceManager.GetString("TestInfoTestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total question.
        /// </summary>
        internal static string TestInfoTotalQuestion {
            get {
                return ResourceManager.GetString("TestInfoTotalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string TestInfoTotalTime {
            get {
                return ResourceManager.GetString("TestInfoTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test list.
        /// </summary>
        internal static string TestList {
            get {
                return ResourceManager.GetString("TestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test name.
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time done.
        /// </summary>
        internal static string TimeDone {
            get {
                return ResourceManager.GetString("TimeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total question.
        /// </summary>
        internal static string TotalQuestion {
            get {
                return ResourceManager.GetString("TotalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize to server.
        /// </summary>
        internal static string UpToServer {
            get {
                return ResourceManager.GetString("UpToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View result.
        /// </summary>
        internal static string ViewResult {
            get {
                return ResourceManager.GetString("ViewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        internal static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in blank with words.
        /// </summary>
        internal static string WWB {
            get {
                return ResourceManager.GetString("WWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a paragraph with the subject.
        /// </summary>
        internal static string WWP {
            get {
                return ResourceManager.GetString("WWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing with sentence.
        ///Ex: The manager drives an expensive car
        ///-&gt; The expensive car is driven by the manager.
        /// </summary>
        internal static string WWS {
            get {
                return ResourceManager.GetString("WWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing with words.
        ///Ex: It/kind/you/invite/us
        ///-&gt; It&apos;s very kind of you to invite us.
        /// </summary>
        internal static string WWW {
            get {
                return ResourceManager.GetString("WWW", resourceCulture);
            }
        }
    }
}
